version: "3.10"
services:
  web:
    container_name: weather_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
